Repository UST-SEAL-Team-4/Machine-Learning-Finals-Project, pull requests merged in 2024-05, with the labels that each got.

#4 create a GitHub template for pull requests
  .github/pull_request_template.md
Labels: Added files

#8 Exploratory Data Analysis on the VALDO Dataset
  eda_dataset.ipynb
Labels: enhancement

#2 Update code for directory checking
  .gitignore
  final_project.ipynb
Labels: Update

#11 Adjusted the location of x and y in generation of bounding box
  final_project.ipynb
Labels: Update

#17 Submission notebook and updates in the code
  final_project.ipynb
  notebook_for_submission.ipynb
  tpfpfn_count.ipynb
Labels: Added files
